Content:
    Beaver:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: Beaver
        repo: https://github.com/ajacquey/beaver
        menu:
            Examples:
                Poroelasticity: examples/poroelasticity/index.md
                Viscoelasticity: examples/viscoelasticity/index.md
            Documentation:
                Beaver syntax: documentation/beaver.md
                Fluid Properties syntax: documentation/fluid_properties.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
