name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: CI ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        activate-environment: moose
        channels: "conda-forge, https://conda.software.inl.gov/public"
    - name: Install MOOSE packages
      shell: bash -l {0}
      run: |
        mamba install moose-tools moose-libmesh
    - name: Compile and test BEAVER
      shell: bash -l {0}
      run: |
        make test -j 2
    - name: Coverage
      uses: codecov/codecov-action@v3.1.0
      with:
        files: lcov.info
    - name: Documentation
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        mkdir gh-pages
        cd doc
        ./moosedocs.py build --destination ../gh-pages/
    - name: Deploy
      if: runner.os == 'Linux'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
        single-commit: true